name: Linting

on:
  push:
    branches:
      - '**'

jobs:
  JavaFormat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # v2 minimum required
      # Recommended: latest versions of Google Java Format require JDK 11+
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace"

  
  ESLint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Run ESLint
      id: run-ESLint
      run: npx eslint . --ext .js,.jsx,.ts,.tsx --fix
    - name: annotate
      uses: hallee/eslint-action@1.0.3
      if: (steps.run-ESLint.outputs.conclusion == 'failure')&&(${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository }})
      with:
        repo-token: ${{secrets.GITHUB_TOKEN}}      